### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'get_data_path'

### ISSUE THREAD

**Issue by Ulf3000** [revereche/lineart_to_gp#2]
Traceback (most recent call last):
  File "C:\Program Files No Install\BLENDER\Builds\daily\blender-3.5.0-alpha+daily.03ccf37162d3\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\alexm\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\lineart_to_gp.py", line 38, in <module>
    import matplotlib.image as mpimg
  File "C:\Users\alexm\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py", line 879, in <module>
    cbook._get_data_path("matplotlibrc"),
  File "C:\Users\alexm\AppData\Roaming\Python\Python310\site-packages\matplotlib\cbook\__init__.py", line 518, in _get_data_path
    return Path(matplotlib.get_data_path(), *args)
  File "C:\Users\alexm\AppData\Roaming\Python\Python310\site-packages\matplotlib\_api\__init__.py", line 222, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'get_data_path'

-------

any chance you will update this addon ?

**Comment by revereche** [comment]
Probably not, since there's not a lot of enthusiasm for it. This should still work in Blender 2.91, and from there you can import the Grease Pencil object to the current version.

**Comment by revereche** [comment]
Decided to mess with this project again and fixed the problem by removing the (unused) matplotlib dependency!
